-- ==============================================================================
-- RIDESYNC - MOTORCYCLE CONVOY & GROUP RIDE TRACKER DATABASE SCHEMA
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Tabel Anggota Konvoi / Riders (riders)
CREATE TABLE IF NOT EXISTS public.riders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number VARCHAR(30) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    motorcycle_model VARCHAR(80),                 -- Contoh: Honda CBR250RR, Yamaha NMAX, Kawasaki ZX25R
    license_plate VARCHAR(30),                    -- Contoh: B 1234 ABC, L 5678 XY
    avatar_url TEXT,
    role VARCHAR(60) DEFAULT 'Anggota Konvoi',    -- Road Captain, Sweeper, Anggota Konvoi, Medis, Logistik
    operator_name VARCHAR(60),
    region_origin VARCHAR(100),
    emergency_contact VARCHAR(30),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabel Sesi Konvoi & Token Tracking (convoy_sessions)
CREATE TABLE IF NOT EXISTS public.convoy_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token VARCHAR(64) UNIQUE NOT NULL,
    rider_id UUID REFERENCES public.riders(id) ON DELETE CASCADE,
    convoy_name VARCHAR(120) DEFAULT 'Touring Akhir Pekan',
    road_captain_name VARCHAR(100) DEFAULT 'Road Captain (Admin)',
    status VARCHAR(30) DEFAULT 'active',          -- 'active', 'ended', 'rejected', 'standby'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabel Titik Tujuan / Checkpoint Konvoi (checkpoints)
CREATE TABLE IF NOT EXISTS public.checkpoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(120) NOT NULL,                   -- Contoh: 'Puncak Pass Bogor', 'Rest Area KM 57'
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabel Log Telemetri GPS Rider Real-Time (rider_locations)
CREATE TABLE IF NOT EXISTS public.rider_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.convoy_sessions(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    accuracy DOUBLE PRECISION,                    -- Akurasi GPS (meter)
    speed DOUBLE PRECISION,                       -- Kecepatan motor (km/h)
    heading DOUBLE PRECISION,                     -- Arah kompas (derajat)
    altitude DOUBLE PRECISION,
    battery_level INTEGER,                        -- Baterai HP rider (%)
    is_charging BOOLEAN DEFAULT FALSE,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Indeks untuk Query Cepat
CREATE INDEX IF NOT EXISTS idx_convoy_token ON public.convoy_sessions(token);
CREATE INDEX IF NOT EXISTS idx_rider_locations_session ON public.rider_locations(session_id);
CREATE INDEX IF NOT EXISTS idx_rider_locations_created ON public.rider_locations(created_at DESC);

-- 6. Row Level Security
ALTER TABLE public.riders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.convoy_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read riders" ON public.riders FOR SELECT USING (true);
CREATE POLICY "Allow public insert riders" ON public.riders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update riders" ON public.riders FOR UPDATE USING (true);

CREATE POLICY "Allow public read convoy_sessions" ON public.convoy_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert convoy_sessions" ON public.convoy_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update convoy_sessions" ON public.convoy_sessions FOR UPDATE USING (true);

CREATE POLICY "Allow public read checkpoints" ON public.checkpoints FOR SELECT USING (true);
CREATE POLICY "Allow public insert checkpoints" ON public.checkpoints FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update checkpoints" ON public.checkpoints FOR UPDATE USING (true);

CREATE POLICY "Allow public read rider_locations" ON public.rider_locations FOR SELECT USING (true);
CREATE POLICY "Allow public insert rider_locations" ON public.rider_locations FOR INSERT WITH CHECK (true);
